[package]
name = "cboragen-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
cboragen-runtime = { path = "../runtime" }
minicbor = { version = "0.25", features = ["derive", "alloc"] }
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "roundtrip"
harness = false
